version: 2.1
jobs:
  build:
    working_directory: ~/collection-editor
    docker:
      - image: circleci/node:6.10-browsers
        environment:
           version_number: $CIRCLE_BRANCH
     
    steps:
      - checkout:
          path: ~/collection-editor
      
      - restore_cache:
          key: ce-dependency-cache-{{ checksum "package.json" }}
       
      - run:
          name: clone plugins
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
            target_branch=$CIRCLE_BRANCH
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            else
            prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird-collection-editor/pulls/$CIRCLE_PR_NUMBER)
            target_branch=$(echo "${prdata}" | jq -r '.base.ref')
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch
            fi

      - run: sudo npm install -g bower@1.8.0 grunt-cli@1.2.0 gulp@3.9.1 codacy-coverage
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower install --force --allow-root
      - run: gulp packageCorePlugins
      - run: npm run collection-plugins
      - run: npm run build
      
      - run: 
          name: test-with-coverage
          command: 'npm run test'
      
      - run: mkdir -p /tmp/coverage && cp /home/circleci/collection-editor/coverage/PhantomJS\ 2.1.1\ \(Linux\ 0.0.0\)/lcov.info /tmp/coverage

      - store_artifacts:
          path: /tmp/coverage
          destination: coverage

      - run: 
          name: Install sonar scanner
          command: 'sudo npm install -g sonarqube-scanner'    
           
      - run: 
          name: Sonar scanner
          command: |
            sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-collection-editor -Dsonar.organization=project-sunbird -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.language=js

      - save_cache:
          key: ce-dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build